(defn solve [n] (if (< n 2) 0 (loop [d 2] (cond (> (* d d) n) 1 (zero? (mod n d)) 0 :else (recur (inc d))))))

(println (solve 0))
(println (solve 1))
(println (solve 2))
(println (solve 3))
(println (solve 4))
(println (solve 25))
(println (solve 97))
(println (solve 121))
(println (solve 997))
